/* tslint:disable */
/* eslint-disable */
import { GraphQLResolveInfo } from 'graphql';
/**
 * This file is auto-generated by @jlowcs/graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */

export {};

declare global {
  namespace GQL {
    /*******************************
     *                             *
     *          TYPE DEFS          *
     *                             *
     *******************************/
    /**
     *  used for logging in
     */
    export interface InputLogin {
      email: string;
      password: string;
    }

    /**
     *  used for creating a new user
     */
    export interface InputRegisterUser {
      name: string;
      email: string;
      password: string;
    }

    export interface Mutation {
      _empty?: string;

      /**
       *  register a new user
       */
      registerUser?: User;
    }

    /**
     *  a type defining a user's public data
     */
    export interface PublicUser {
      id?: string;
      name?: string;
      email?: string;
    }

    export interface Query {
      _empty?: string;

      /**
       *  login as a user
       */
      loginUser?: User;

      /**
       *  get a user's public data
       */
      getUser?: PublicUser;
    }

    export interface Subscription {
      _empty?: string;
    }

    /**
     *  a type defining a user
     */
    export interface User {
      id?: string;
      name?: string;
      email?: string;
      token?: string;
    }

    /*********************************
     *                               *
     *         TYPE RESOLVERS        *
     *                               *
     *********************************/
    /**
     * This interface define the shape of your resolver
     * Note that this type is designed to be compatible with graphql-tools resolvers
     * However, you can still use other generated interfaces to make your resolver type-safed
     */
    export interface Resolver {
      Mutation?: MutationTypeResolver;
      PublicUser?: PublicUserTypeResolver;
      Query?: QueryTypeResolver;
      Subscription?: SubscriptionTypeResolver;
      User?: UserTypeResolver;
    }
    export interface MutationTypeResolver<TParent = any> {
      _empty?: MutationTo_emptyResolver<TParent>;
      registerUser?: MutationToRegisterUserResolver<TParent>;
    }

    export interface MutationTo_emptyResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface MutationToRegisterUserArgs {
      input: InputRegisterUser;
    }
    export interface MutationToRegisterUserResolver<TParent = any, TResult = any> {
      (parent: TParent, args: MutationToRegisterUserArgs, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface PublicUserTypeResolver<TParent = any> {
      id?: PublicUserToIdResolver<TParent>;
      name?: PublicUserToNameResolver<TParent>;
      email?: PublicUserToEmailResolver<TParent>;
    }

    export interface PublicUserToIdResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface PublicUserToNameResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface PublicUserToEmailResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface QueryTypeResolver<TParent = any> {
      _empty?: QueryTo_emptyResolver<TParent>;
      loginUser?: QueryToLoginUserResolver<TParent>;
      getUser?: QueryToGetUserResolver<TParent>;
    }

    export interface QueryTo_emptyResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface QueryToLoginUserArgs {
      input: InputLogin;
    }
    export interface QueryToLoginUserResolver<TParent = any, TResult = any> {
      (parent: TParent, args: QueryToLoginUserArgs, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface QueryToGetUserArgs {
      id: string;
    }
    export interface QueryToGetUserResolver<TParent = any, TResult = any> {
      (parent: TParent, args: QueryToGetUserArgs, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface SubscriptionTypeResolver<TParent = any> {
      _empty?: SubscriptionTo_emptyResolver<TParent>;
    }

    export interface SubscriptionTo_emptyResolver<TParent = any, TResult = any> {
      resolve?: (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo) => TResult;
      subscribe: (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo) => AsyncIterator<TResult>;
    }

    export interface UserTypeResolver<TParent = any> {
      id?: UserToIdResolver<TParent>;
      name?: UserToNameResolver<TParent>;
      email?: UserToEmailResolver<TParent>;
      token?: UserToTokenResolver<TParent>;
    }

    export interface UserToIdResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface UserToNameResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface UserToEmailResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }

    export interface UserToTokenResolver<TParent = any, TResult = any> {
      (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
    }
  }
}
